WIP: Feature
dNationCloud/ping pull request #18
Opened 2021-01-19 16:32 UTC by MlsnyLisiak

2021-01-19 16:44 UTC, MlsnyLisiak commented
zabudol som bumpnut verziu mam zly spacing v ping-dashboard.yaml ... zajtra rano to fixnem

2021-01-20 11:09 UTC, matofeder requested changes

2021-01-20 11:09 UTC, matofeder commented on docker/helpers/dnation_brand.sh
> +#!/bin/bash
There is already `docker/grafana/dnation/brand.sh` file which is used in the docker-compose manifest. 
Probably copy/paste error.

2021-01-20 11:51 UTC, matofeder approved these changes

2021-01-20 13:47 UTC, merged